---

- name: backup the database and images of the big algae open experiment website
  hosts: vagrant_centos7
  
  tasks: 
    - name: copy across backups folder
      synchronize: mode=pull
                   src=/var/www/html/baoe-app/backups
                   dest=../
                   archive=yes
