---

- name: provision flask web server
  hosts: all
  
  tasks: 
    - name: copy across website files
      copy: src=../baoe-app/
            dest=/var/www/html/baoe-app/app
            
    - name: restart apache
      service: name=httpd
               state=restarted