---

- name: provision flask web server
  hosts: all
  
  tasks: 
    #- name: update the system
      #yum: name=*
           #state=latest

    - name: add the epel repository
      yum: name=epel-release
           state=present                   
                   
    - name: add the mongo repository
      copy: src=../server_configuration_files/mongodb-org-2.4.repo
            dest=/etc/yum.repos.d
                   
    - name: install necessary software
      yum: name={{ item }}
           state=present
      with_items:
        - httpd
        - mod_wsgi
        - firewalld
        - python-pip
        - python-virtualenv
        - mongodb-org
        - wkhtmltopdf
        - xorg-x11-server-Xvfb
        - urw-fonts
    
    - name: start firewalld
      service: name=firewalld
               enabled=yes
               state=started
    
    - name: start apache
      service: name=httpd
               enabled=yes
               state=started
            
    - name: open up http port
      firewalld: service=http
                 permanent=yes
                 state=enabled
      notify: restart firewalld

    - name: create a python virtual environment
      command: virtualenv /var/www/html/baoe-app/env
            
    - name: install necessary python packages
      pip: name={{ item }}
           virtualenv=/var/www/html/baoe-app/env
      with_items:
        - pymongo
        - flask
        - markdown
        - pdfkit
            
    - name: copy across website files
      copy: src=../baoe-app/
            dest=/var/www/html/baoe-app/app
            
    - name: start mongodb
      service: name=mongod
               enabled=yes
               state=started
            
    - name: copy across wsgi file
      copy: src=../server_configuration_files/app.wsgi
            dest=/var/www/html/baoe-app/

    - name: copy across Google Password file
      copy: src=../.google_password
            dest=/var/www/html/baoe-app/
            
    - name: this error http://ca3.php.net/manual/en/mongo.installation.php#mongo.installation.fedora
      command: /usr/sbin/setsebool -P httpd_can_network_connect 1
      notify: restart apache
      when: "'vagrant' in group_names"

    - name: this error https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2267
      command: /usr/sbin/setsebool -P httpd_execmem on
      notify: restart apache
      when: "'vagrant' in group_names"

    - name: copy across apache configuration file
      copy: src=../server_configuration_files/baoe-app.conf
            dest=/etc/httpd/conf.d/baoe-app.conf
      notify: restart apache
            
    - name: create virtualx environment
      script: ../server_configuration_files/setup_virtualx_env.sh
              creates=/usr/local/bin/wkhtmltopdf
              
    - name: create image folder
      command: mkdir -p /var/www/html/baoe-app/images

    - name: change owner of image folder
      command: chown -R apache:apache /var/www/html/baoe-app/images
    
    - name: change context of image folder
      command: chcon -R system_u:object_r:httpd_sys_rw_content_t /var/www/html/baoe-app/images
              
    - name: copy across mongodb backup script
      copy: src=../server_configuration_files/mongodump_backup.sh
            dest=/var/www/html/baoe-app/

    - name: make the mongodb backup script executable
      command: chmod +x /var/www/html/baoe-app/mongodump_backup.sh

    - name: create a cron job which performs a backup of the database every 12 hours
      cron: name="backup database"
            job="/var/www/html/baoe-app/mongodump_backup.sh"
            minute="0"
            hour="*/12"

  handlers:
  
    - name: restart firewalld
      service: name=firewalld
               state=restarted
               
    - name: restart apache
      service: name=httpd
               state=restarted