---

- name: provision flask web server
  hosts: all
  
  tasks: 
    - name: copy across backups folder
      synchronize: src=../backups
                   dest=/var/www/html/baoe-app
                   archive=yes
                   rsync_path="sudo rsync"
    
    - name: restore the database
      script: ../server_configuration_files/mongorestore.sh
